### PR TITLE
load sys.config env

### PR DESCRIPTION
**Pull request by grw-rs**

### CODE REVIEW

**Comment by uwiger** [comment]
So what happens if we build a system that has its own `sys.config`? Shouldn't that override any settings in the `aeternity` config?

**Comment by uwiger** [comment]
It might be necessary to describe a variable loading sequence. The normal one is:
`application env` - `sys.config` - `command-line args`

In this case, it seems reasonable to apply the `aeternity` config before the system config, but this would require re-applying the vars that need to override (not forgetting command-line args).

An alternative might be to figure something out at build time.

**Comment by grw-rs** [comment]
> So what happens if we build a system that has its own `sys.config`? Shouldn't that override any settings in the `aeternity` config?

When the `sys.config` is under `node_root` path specified in Elixir config, I suppose it's safe to assume that config file belongs to Aeternity node. (if needed, we can add a Elixir config option specifying non-standard placement of sys.config) 

The `sys.config` is read before aecore starts up, so there won't be a clash. Here we are supplying a work on startup which is happening by default in Erlang, but not in Elixir (since Elixir doesn't use it).

**Review by uwiger — APPROVED** [review]
Let's go with this for now. We may revisit later if it turns out that we need something more complete.

**Pull request merged**
